import './globals.css';

import { Geist, Geist_Mono } from 'next/font/google';

import { EscrowProvider } from '@/providers/scrow.provider';
import type { Metadata } from 'next';
import { Toaster } from 'sonner';
import { TrustlessWorkProvider } from '@/providers/TrustlessWorkProvider';
import { WalletProvider } from '@/components/onboarding/WalletContext';

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <TrustlessWorkProvider>
          <WalletProvider>
            <EscrowProvider>
              <main>{children}</main>
              <Toaster position="top-right" />
            </EscrowProvider>
          </WalletProvider>
        </TrustlessWorkProvider>
      </body>
    </html>
  );
}
